# Generated by Django 2.0.7 on 2019-03-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(blank=True, null=True, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('role', models.CharField(choices=[('T', 'teacher'), ('S', 'student'), ('M', 'Manager')], max_length=1)),
            ],
        ),
    ]
