# Generated by Django 2.0.7 on 2019-03-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_PROJ', '0002_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_file', models.FileField(upload_to='static/upload')),
            ],
        ),
    ]
