# Generated by Django 2.0.7 on 2019-03-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_PROJ', '0003_train_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_model', models.CharField(default='Predict_Gross', max_length=30)),
                ('optimizer', models.CharField(default='tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)', max_length=1000)),
                ('cost', models.CharField(default='tf.sqrt(tf.reduce_mean(tf.square(tf.subtract(Y_pred, Y))))', max_length=1000)),
                ('learning_rate', models.DecimalField(decimal_places=4, default=0.001, max_digits=5)),
                ('batch_size', models.IntegerField(default=500)),
                ('epochs', models.IntegerField(default=20)),
                ('pca_num', models.IntegerField(default=3)),
            ],
        ),
    ]
