# Generated by Django 2.0.7 on 2019-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_PROJ', '0004_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(default='Avatar', max_length=1500)),
                ('predict_type', models.CharField(default='Predict_Gross', max_length=100)),
            ],
        ),
    ]
